// Generated by an automated build step. Do not edit.

package types

import "time"

type ApiError struct {
	Code string `json:"code"`
	Details map[string]interface{} `json:"details,omitempty"`
	Message string `json:"message"`
	RequestId *string `json:"requestId,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

type CreateDocumentRequest struct {
	Content *string `json:"content,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Title string `json:"title"`
	WorkspaceId string `json:"workspaceId"`
}

type CreateUserRequest struct {
	Email string `json:"email"`
	Name string `json:"name"`
	Role *UserRole `json:"role,omitempty"`
}

// Document A document in a workspace
type Document struct {
	// A user account
	Author *User `json:"author,omitempty"`
	AuthorId string `json:"authorId"`
	// Document content in Markdown
	Content *string `json:"content,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	ID string `json:"id"`
	LastViewedAt *time.Time `json:"lastViewedAt,omitempty"`
	Status *DocumentStatus `json:"status,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Title string `json:"title"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	ViewCount *int `json:"viewCount,omitempty"`
	WorkspaceId string `json:"workspaceId"`
}

// DocumentStatus 
type DocumentStatus string

const (
	DocumentStatusDraft DocumentStatus = "draft"
	DocumentStatusPublished DocumentStatus = "published"
	DocumentStatusArchived DocumentStatus = "archived"
)

// MemberRole 
type MemberRole string

const (
	MemberRoleOwner MemberRole = "owner"
	MemberRoleAdmin MemberRole = "admin"
	MemberRoleMember MemberRole = "member"
	MemberRoleViewer MemberRole = "viewer"
)

type PaginatedResponse struct {
	HasNext *bool `json:"hasNext,omitempty"`
	HasPrev *bool `json:"hasPrev,omitempty"`
	Items []interface{} `json:"items"`
	Page int `json:"page"`
	PageSize int `json:"pageSize"`
	Total int `json:"total"`
}

// PlanType 
type PlanType string

const (
	PlanTypeFree PlanType = "free"
	PlanTypePro PlanType = "pro"
	PlanTypeEnterprise PlanType = "enterprise"
)

type UpdateDocumentRequest struct {
	Content *string `json:"content,omitempty"`
	Status *DocumentStatus `json:"status,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Title *string `json:"title,omitempty"`
}

type UpdateUserRequest struct {
	AvatarUrl *string `json:"avatarUrl,omitempty"`
	Name *string `json:"name,omitempty"`
	Role *UserRole `json:"role,omitempty"`
}

// User A user account
type User struct {
	AvatarUrl *string `json:"avatarUrl,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	Email string `json:"email"`
	ID string `json:"id"`
	Name string `json:"name"`
	Role *UserRole `json:"role,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// UserRole 
type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleMember UserRole = "member"
	UserRoleGuest UserRole = "guest"
)

// Workspace A workspace/organization
type Workspace struct {
	CreatedAt time.Time `json:"createdAt"`
	Description *string `json:"description,omitempty"`
	ID string `json:"id"`
	MemberCount *int `json:"memberCount,omitempty"`
	Name string `json:"name"`
	Plan PlanType `json:"plan"`
	Slug string `json:"slug"`
}

// WorkspaceMember A user's membership in a workspace
type WorkspaceMember struct {
	JoinedAt time.Time `json:"joinedAt"`
	Role MemberRole `json:"role"`
	// A user account
	User *User `json:"user,omitempty"`
	UserId string `json:"userId"`
	WorkspaceId string `json:"workspaceId"`
}
