// Generated by an automated build step. Do not edit.

export namespace Users {
  /** A user account */
  export interface User {
    avatarUrl?: string;
    createdAt: string;
    email: string;
    id: string;
    name: string;
    role?: UserRole;
    updatedAt?: string;
  }
  export enum UserRole {
    Admin = "admin",
    Member = "member",
    Guest = "guest",
  }
  export interface CreateUserRequest {
    email: string;
    name: string;
    role?: UserRole;
  }
  export interface UpdateUserRequest {
    avatarUrl?: string | null;
    name?: string;
    role?: UserRole;
  }
}

export namespace Workspaces {
  /** A workspace/organization */
  export interface Workspace {
    createdAt: string;
    description?: string;
    id: string;
    memberCount?: number;
    name: string;
    plan: PlanType;
    slug: string;
  }
  export enum PlanType {
    Free = "free",
    Pro = "pro",
    Enterprise = "enterprise",
  }
  /** A user's membership in a workspace */
  export interface WorkspaceMember {
    joinedAt: string;
    role: MemberRole;
    /** A user account */
    user?: Users.User;
    userId: string;
    workspaceId: string;
  }
  export enum MemberRole {
    Owner = "owner",
    Admin = "admin",
    Member = "member",
    Viewer = "viewer",
  }
}

export namespace Documents {
  /** A document in a workspace */
  export interface Document {
    /** A user account */
    author?: Users.User;
    authorId: string;
    /** Document content in Markdown */
    content?: string;
    createdAt: string;
    id: string;
    lastViewedAt?: string;
    status?: DocumentStatus;
    tags?: Array<string>;
    title: string;
    updatedAt?: string;
    viewCount?: number;
    workspaceId: string;
  }
  export enum DocumentStatus {
    Draft = "draft",
    Published = "published",
    Archived = "archived",
  }
  export interface CreateDocumentRequest {
    content?: string;
    tags?: Array<string>;
    title: string;
    workspaceId: string;
  }
  export interface UpdateDocumentRequest {
    content?: string;
    status?: DocumentStatus;
    tags?: Array<string>;
    title?: string;
  }
}

export namespace Common {
  export interface PaginatedResponse {
    hasNext?: boolean;
    hasPrev?: boolean;
    items: Array<unknown>;
    page: number;
    pageSize: number;
    total: number;
  }
  export interface ApiError {
    code: string;
    details?: Record<string, unknown>;
    message: string;
    requestId?: string;
    timestamp?: string;
  }
}
