# Generated by an automated build step. Do not edit.

from typing import TypedDict, NotRequired, Literal, Union, List, Dict, Any
from enum import Enum

class ApiError(TypedDict):
    code: str
    details: NotRequired[Dict[str, Any]]
    message: str
    request_id: NotRequired[str]
    timestamp: NotRequired[str]

class CreateDocumentRequest(TypedDict):
    content: NotRequired[str]
    tags: NotRequired[List[str]]
    title: str
    workspace_id: str

class CreateUserRequest(TypedDict):
    email: str
    name: str
    role: NotRequired["UserRole"]

class Document(TypedDict):
    """A document in a workspace"""
    author: NotRequired["User"]
    """A user account"""

    author_id: str
    content: NotRequired[str]
    """Document content in Markdown"""

    created_at: str
    id: str
    last_viewed_at: NotRequired[str]
    status: NotRequired["DocumentStatus"]
    tags: NotRequired[List[str]]
    title: str
    updated_at: NotRequired[str]
    view_count: NotRequired[int]
    workspace_id: str

class DocumentStatus(str, Enum):
    DRAFT = "draft"
    PUBLISHED = "published"
    ARCHIVED = "archived"

class MemberRole(str, Enum):
    OWNER = "owner"
    ADMIN = "admin"
    MEMBER = "member"
    VIEWER = "viewer"

class PaginatedResponse(TypedDict):
    has_next: NotRequired[bool]
    has_prev: NotRequired[bool]
    items: List[Any]
    page: int
    page_size: int
    total: int

class PlanType(str, Enum):
    FREE = "free"
    PRO = "pro"
    ENTERPRISE = "enterprise"

class UpdateDocumentRequest(TypedDict, total=False):
    content: str
    status: "DocumentStatus"
    tags: List[str]
    title: str

class UpdateUserRequest(TypedDict, total=False):
    avatar_url: str | None
    name: str
    role: "UserRole"

class User(TypedDict):
    """A user account"""
    avatar_url: NotRequired[str]
    created_at: str
    email: str
    id: str
    name: str
    role: NotRequired["UserRole"]
    updated_at: NotRequired[str]

class UserRole(str, Enum):
    ADMIN = "admin"
    MEMBER = "member"
    GUEST = "guest"

class Workspace(TypedDict):
    """A workspace/organization"""
    created_at: str
    description: NotRequired[str]
    id: str
    member_count: NotRequired[int]
    name: str
    plan: "PlanType"
    slug: str

class WorkspaceMember(TypedDict):
    """A user's membership in a workspace"""
    joined_at: str
    role: "MemberRole"
    user: NotRequired["User"]
    """A user account"""

    user_id: str
    workspace_id: str
