// Generated by an automated build step. Do not edit.

import * as z from "zod";

export const addToCartRequestSchema = z.object({
  productId: z.string().uuid(),
  quantity: z.number().int().min(1),
});
export const addressSchema = z.object({
  city: z.string(),
  country: z.string().regex(/^[A-Z]{2}$/),
  line1: z.string(),
  line2: z.string().optional(),
  postalCode: z.string(),
  state: z.string().optional(),
});
export const apiErrorSchema = z.object({
  code: z.string(),
  details: z.array(z.lazy(() => errorDetailSchema)).optional(),
  message: z.string(),
  requestId: z.string().optional(),
});
export const cartSchema = z.object({
  id: z.string().uuid(),
  itemCount: z.number().int().optional(),
  items: z.array(z.lazy(() => cartItemSchema)),
  subtotal: z.lazy(() => priceSchema),
});
export const cartItemSchema = z.object({
  price: z.lazy(() => priceSchema),
  product: z.lazy(() => productSchema).optional(),
  productId: z.string().uuid(),
  quantity: z.number().int().min(1),
});
export const createOrderRequestSchema = z.object({
  billingAddress: z.lazy(() => addressSchema).optional(),
  notes: z.string().max(500).optional(),
  shippingAddress: z.lazy(() => addressSchema),
});
export const createProductRequestSchema = z.object({
  category: z.lazy(() => productCategorySchema),
  description: z.string().optional(),
  images: z.array(z.unknown()).optional(),
  name: z.string().min(1).max(200),
  price: z.unknown(),
  stockCount: z.number().int().min(0).optional(),
  tags: z.array(z.string()).optional(),
});
export const errorDetailSchema = z.object({
  code: z.string().optional(),
  field: z.string(),
  message: z.string(),
});
export const orderSchema = z.object({
  billingAddress: z.lazy(() => addressSchema).optional(),
  createdAt: z.string().datetime(),
  id: z.string().uuid(),
  items: z.array(z.lazy(() => orderItemSchema)),
  shippingAddress: z.lazy(() => addressSchema),
  status: z.lazy(() => orderStatusSchema),
  total: z.lazy(() => priceSchema),
  updatedAt: z.string().datetime().optional(),
});
export const orderItemSchema = z.object({
  productId: z.string().uuid(),
  productName: z.string(),
  quantity: z.number().int().min(1),
  totalPrice: z.lazy(() => priceSchema),
  unitPrice: z.lazy(() => priceSchema),
});
export const orderStatusSchema = z.enum(["pending", "confirmed", "processing", "shipped", "delivered", "cancelled"]);
export const priceSchema = z.object({
  amount: z.number().min(0),
  currency: z.string().regex(/^[A-Z]{3}$/),
  formatted: z.string().optional(),
});
export const productSchema = z.object({
  category: z.lazy(() => productCategorySchema),
  createdAt: z.string().datetime().optional(),
  description: z.string().optional(),
  id: z.string().uuid(),
  images: z.array(z.lazy(() => productImageSchema)).optional(),
  inStock: z.boolean(),
  name: z.string().min(1).max(200),
  price: z.lazy(() => priceSchema),
  stockCount: z.number().int().min(0).optional(),
  tags: z.array(z.string()).optional(),
});
export const productCategorySchema = z.enum(["electronics", "clothing", "home", "books", "sports", "toys"]);
export const productImageSchema = z.object({
  alt: z.string(),
  isPrimary: z.boolean().optional(),
  url: z.string().url(),
});
export const productListResponseSchema = z.object({
  hasMore: z.boolean().optional(),
  items: z.array(z.lazy(() => productSchema)),
  limit: z.number().int(),
  offset: z.number().int(),
  total: z.number().int(),
});

// Internal schema types
type AddToCartRequestSchemaType = z.infer<typeof addToCartRequestSchema>;
type AddressSchemaType = z.infer<typeof addressSchema>;
type ApiErrorSchemaType = z.infer<typeof apiErrorSchema>;
type CartSchemaType = z.infer<typeof cartSchema>;
type CartItemSchemaType = z.infer<typeof cartItemSchema>;
type CreateOrderRequestSchemaType = z.infer<typeof createOrderRequestSchema>;
type CreateProductRequestSchemaType = z.infer<typeof createProductRequestSchema>;
type ErrorDetailSchemaType = z.infer<typeof errorDetailSchema>;
type OrderSchemaType = z.infer<typeof orderSchema>;
type OrderItemSchemaType = z.infer<typeof orderItemSchema>;
type OrderStatusSchemaType = z.infer<typeof orderStatusSchema>;
type PriceSchemaType = z.infer<typeof priceSchema>;
type ProductSchemaType = z.infer<typeof productSchema>;
type ProductCategorySchemaType = z.infer<typeof productCategorySchema>;
type ProductImageSchemaType = z.infer<typeof productImageSchema>;
type ProductListResponseSchemaType = z.infer<typeof productListResponseSchema>;

// TypeScript interfaces
/** Request to add an item to cart */
export interface AddToCartRequest {
  productId: AddToCartRequestSchemaType["productId"];
  quantity: AddToCartRequestSchemaType["quantity"];
}
/** Physical address */
export interface Address {
  city: AddressSchemaType["city"];
  /** ISO 3166-1 alpha-2 country code */
  country: AddressSchemaType["country"];
  line1: AddressSchemaType["line1"];
  line2?: AddressSchemaType["line2"];
  postalCode: AddressSchemaType["postalCode"];
  state?: AddressSchemaType["state"];
}
/** API error response */
export interface ApiError {
  /** Machine-readable error code */
  code: ApiErrorSchemaType["code"];
  details?: ApiErrorSchemaType["details"];
  /** Human-readable error message */
  message: ApiErrorSchemaType["message"];
  /** Request ID for debugging */
  requestId?: ApiErrorSchemaType["requestId"];
}
/** Shopping cart */
export interface Cart {
  id: CartSchemaType["id"];
  /** Total number of items in cart */
  itemCount?: CartSchemaType["itemCount"];
  items: CartSchemaType["items"];
  /** Price with currency */
  subtotal: CartSchemaType["subtotal"];
}
/** Item in a shopping cart */
export interface CartItem {
  /** Price with currency */
  price: CartItemSchemaType["price"];
  /** A product available for purchase */
  product?: CartItemSchemaType["product"];
  productId: CartItemSchemaType["productId"];
  quantity: CartItemSchemaType["quantity"];
}
/** Request to create an order */
export interface CreateOrderRequest {
  /** Physical address */
  billingAddress?: CreateOrderRequestSchemaType["billingAddress"];
  notes?: CreateOrderRequestSchemaType["notes"];
  /** Physical address */
  shippingAddress: CreateOrderRequestSchemaType["shippingAddress"];
}
/** Request body for creating a product */
export interface CreateProductRequest {
  /** Product category */
  category: CreateProductRequestSchemaType["category"];
  description?: CreateProductRequestSchemaType["description"];
  images?: CreateProductRequestSchemaType["images"];
  name: CreateProductRequestSchemaType["name"];
  price: CreateProductRequestSchemaType["price"];
  stockCount?: CreateProductRequestSchemaType["stockCount"];
  tags?: CreateProductRequestSchemaType["tags"];
}
/** Detailed error information */
export interface ErrorDetail {
  /** Error code for this field */
  code?: ErrorDetailSchemaType["code"];
  /** Field that caused the error */
  field: ErrorDetailSchemaType["field"];
  /** Error description */
  message: ErrorDetailSchemaType["message"];
}
/** A customer order */
export interface Order {
  /** Physical address */
  billingAddress?: OrderSchemaType["billingAddress"];
  createdAt: OrderSchemaType["createdAt"];
  id: OrderSchemaType["id"];
  items: OrderSchemaType["items"];
  /** Physical address */
  shippingAddress: OrderSchemaType["shippingAddress"];
  /** Order status */
  status: OrderSchemaType["status"];
  /** Price with currency */
  total: OrderSchemaType["total"];
  updatedAt?: OrderSchemaType["updatedAt"];
}
/** Item in an order */
export interface OrderItem {
  productId: OrderItemSchemaType["productId"];
  productName: OrderItemSchemaType["productName"];
  quantity: OrderItemSchemaType["quantity"];
  /** Price with currency */
  totalPrice: OrderItemSchemaType["totalPrice"];
  /** Price with currency */
  unitPrice: OrderItemSchemaType["unitPrice"];
}
/** Order status */
export type OrderStatus = OrderStatusSchemaType;
/** Price with currency */
export interface Price {
  /** Price amount in smallest currency unit (cents) */
  amount: PriceSchemaType["amount"];
  /** ISO 4217 currency code */
  currency: PriceSchemaType["currency"];
  /** Human-readable formatted price */
  readonly formatted?: PriceSchemaType["formatted"];
}
/** A product available for purchase */
export interface Product {
  /** Product category */
  category: ProductSchemaType["category"];
  readonly createdAt?: ProductSchemaType["createdAt"];
  /** Detailed product description */
  description?: ProductSchemaType["description"];
  /** Unique product identifier */
  id: ProductSchemaType["id"];
  images?: ProductSchemaType["images"];
  /** Whether the product is currently in stock */
  inStock: ProductSchemaType["inStock"];
  /** Product name */
  name: ProductSchemaType["name"];
  /** Price with currency */
  price: ProductSchemaType["price"];
  /** Number of items in stock */
  stockCount?: ProductSchemaType["stockCount"];
  tags?: ProductSchemaType["tags"];
}
/** Product category */
export type ProductCategory = ProductCategorySchemaType;
/** Product image */
export interface ProductImage {
  alt: ProductImageSchemaType["alt"];
  isPrimary?: ProductImageSchemaType["isPrimary"];
  url: ProductImageSchemaType["url"];
}
/** Paginated list of products */
export interface ProductListResponse {
  hasMore?: ProductListResponseSchemaType["hasMore"];
  items: ProductListResponseSchemaType["items"];
  limit: ProductListResponseSchemaType["limit"];
  offset: ProductListResponseSchemaType["offset"];
  /** Total number of products matching the query */
  total: ProductListResponseSchemaType["total"];
}