package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hntrl/sparktype/internal/config"
	"github.com/hntrl/sparktype/internal/contents"
	"github.com/hntrl/sparktype/internal/generators"
	"github.com/hntrl/sparktype/internal/spec"

	// Register generators for testing
	_ "github.com/hntrl/sparktype/internal/generators/golang"
	_ "github.com/hntrl/sparktype/internal/generators/python"
	_ "github.com/hntrl/sparktype/internal/generators/typescript"
	_ "github.com/hntrl/sparktype/internal/generators/zod"
)

func TestProcessOutput_TypeScript(t *testing.T) {
	// Create temp directory for output
	tmpDir, err := os.MkdirTemp("", "sparktype-test-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	// Setup test data
	testDataDir, _ := filepath.Abs("testdata")
	registry := spec.NewRegistry(map[string]config.Spec{
		"api": {Path: filepath.Join(testDataDir, "simple.yaml")},
	}, testDataDir)

	output := config.Output{
		Path:     filepath.Join(tmpDir, "types.ts"),
		Format:   "typescript",
		Contents: []config.ContentItem{{Pattern: "api:*"}},
	}

	err = processOutput(registry, output, config.Options{}, tmpDir)
	if err != nil {
		t.Fatalf("processOutput failed: %v", err)
	}

	// Verify output file exists
	content, err := os.ReadFile(output.Path)
	if err != nil {
		t.Fatalf("failed to read output: %v", err)
	}

	// Check content contains expected elements
	contentStr := string(content)
	expectedStrings := []string{
		"Generated by an automated build step",
		"export interface User",
		"id: number",
		"email: string",
		"export type Status",
	}

	for _, expected := range expectedStrings {
		if !strings.Contains(contentStr, expected) {
			t.Errorf("output missing expected string: %q", expected)
		}
	}
}

func TestProcessOutput_Zod(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "sparktype-test-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	testDataDir, _ := filepath.Abs("testdata")
	registry := spec.NewRegistry(map[string]config.Spec{
		"api": {Path: filepath.Join(testDataDir, "simple.yaml")},
	}, testDataDir)

	output := config.Output{
		Path:     filepath.Join(tmpDir, "schemas.ts"),
		Format:   "zod",
		Contents: []config.ContentItem{{Pattern: "api:*"}},
	}

	err = processOutput(registry, output, config.Options{}, tmpDir)
	if err != nil {
		t.Fatalf("processOutput failed: %v", err)
	}

	content, err := os.ReadFile(output.Path)
	if err != nil {
		t.Fatalf("failed to read output: %v", err)
	}

	contentStr := string(content)
	expectedStrings := []string{
		"import * as z from \"zod\"",
		"userSchema",
		"z.object",
		"z.number",
		"z.string",
	}

	for _, expected := range expectedStrings {
		if !strings.Contains(contentStr, expected) {
			t.Errorf("output missing expected string: %q", expected)
		}
	}
}

func TestProcessOutput_Python(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "sparktype-test-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	testDataDir, _ := filepath.Abs("testdata")
	registry := spec.NewRegistry(map[string]config.Spec{
		"api": {Path: filepath.Join(testDataDir, "simple.yaml")},
	}, testDataDir)

	output := config.Output{
		Path:     filepath.Join(tmpDir, "types.py"),
		Format:   "python",
		Contents: []config.ContentItem{{Pattern: "api:*"}},
	}

	err = processOutput(registry, output, config.Options{}, tmpDir)
	if err != nil {
		t.Fatalf("processOutput failed: %v", err)
	}

	content, err := os.ReadFile(output.Path)
	if err != nil {
		t.Fatalf("failed to read output: %v", err)
	}

	contentStr := string(content)
	expectedStrings := []string{
		"from typing import",
		"TypedDict",
		"class User",
		"id: int",
		"email: str",
	}

	for _, expected := range expectedStrings {
		if !strings.Contains(contentStr, expected) {
			t.Errorf("output missing expected string: %q", expected)
		}
	}
}

func TestProcessOutput_Go(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "sparktype-test-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	testDataDir, _ := filepath.Abs("testdata")
	registry := spec.NewRegistry(map[string]config.Spec{
		"api": {Path: filepath.Join(testDataDir, "simple.yaml")},
	}, testDataDir)

	output := config.Output{
		Path:     filepath.Join(tmpDir, "types.go"),
		Format:   "go",
		Contents: []config.ContentItem{{Pattern: "api:*"}},
	}

	err = processOutput(registry, output, config.Options{}, tmpDir)
	if err != nil {
		t.Fatalf("processOutput failed: %v", err)
	}

	content, err := os.ReadFile(output.Path)
	if err != nil {
		t.Fatalf("failed to read output: %v", err)
	}

	contentStr := string(content)
	expectedStrings := []string{
		"package types",
		"type User struct",
		"ID int",
		"Email string",
	}

	for _, expected := range expectedStrings {
		if !strings.Contains(contentStr, expected) {
			t.Errorf("output missing expected string: %q", expected)
		}
	}
}

func TestProcessOutput_InvalidFormat(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "sparktype-test-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	testDataDir, _ := filepath.Abs("testdata")
	registry := spec.NewRegistry(map[string]config.Spec{
		"api": {Path: filepath.Join(testDataDir, "simple.yaml")},
	}, testDataDir)

	output := config.Output{
		Path:     filepath.Join(tmpDir, "types.txt"),
		Format:   "invalid",
		Contents: []config.ContentItem{{Pattern: "api:*"}},
	}

	err = processOutput(registry, output, config.Options{}, tmpDir)
	if err == nil {
		t.Error("expected error for invalid format, got nil")
	}
}

func TestProcessOutput_InvalidPattern(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "sparktype-test-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	testDataDir, _ := filepath.Abs("testdata")
	registry := spec.NewRegistry(map[string]config.Spec{
		"api": {Path: filepath.Join(testDataDir, "simple.yaml")},
	}, testDataDir)

	output := config.Output{
		Path:     filepath.Join(tmpDir, "types.ts"),
		Format:   "typescript",
		Contents: []config.ContentItem{{Pattern: "nonexistent:*"}},
	}

	err = processOutput(registry, output, config.Options{}, tmpDir)
	if err == nil {
		t.Error("expected error for nonexistent spec, got nil")
	}
}

func TestRunGenerateOnce(t *testing.T) {
	// Create temp directory
	tmpDir, err := os.MkdirTemp("", "sparktype-test-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	// Copy test files to temp dir
	testDataDir, _ := filepath.Abs("testdata")

	// Copy simple.yaml
	specContent, _ := os.ReadFile(filepath.Join(testDataDir, "simple.yaml"))
	os.WriteFile(filepath.Join(tmpDir, "simple.yaml"), specContent, 0644)

	// Use relative output path - this tests that paths are resolved relative to config
	configContent := `{
  "specs": {
    "api": {
      "path": "./simple.yaml"
    }
  },
  "outputs": [
    {
      "path": "./output/types.ts",
      "format": "typescript",
      "contents": ["api:*"]
    }
  ]
}`
	configPath := filepath.Join(tmpDir, "typegen.jsonc")
	os.WriteFile(configPath, []byte(configContent), 0644)

	// Run generation
	err = runGenerateOnce(configPath)
	if err != nil {
		t.Fatalf("runGenerateOnce failed: %v", err)
	}

	// Verify output was created (resolved relative to config directory)
	outputPath := filepath.Join(tmpDir, "output", "types.ts")
	if _, err := os.Stat(outputPath); os.IsNotExist(err) {
		t.Error("output file was not created")
	}
}

func TestContentResolver_Integration(t *testing.T) {
	testDataDir, _ := filepath.Abs("testdata")
	registry := spec.NewRegistry(map[string]config.Spec{
		"api": {Path: filepath.Join(testDataDir, "simple.yaml")},
	}, testDataDir)

	resolver := contents.NewResolver(registry)

	// Test wildcard pattern
	tree, err := resolver.Resolve([]config.ContentItem{
		{Pattern: "api:*"},
	})
	if err != nil {
		t.Fatalf("resolve failed: %v", err)
	}

	if len(tree.Nodes) == 0 {
		t.Error("expected nodes from wildcard pattern")
	}

	// Test specific pattern
	tree, err = resolver.Resolve([]config.ContentItem{
		{Pattern: "api:User"},
	})
	if err != nil {
		t.Fatalf("resolve failed: %v", err)
	}

	if len(tree.Nodes) != 1 {
		t.Errorf("expected 1 node for User, got %d", len(tree.Nodes))
	}
}

func TestGeneratorRegistry_Integration(t *testing.T) {
	// Test that all generators are registered
	formats := []string{"typescript", "zod", "python", "go"}

	for _, format := range formats {
		t.Run(format, func(t *testing.T) {
			gen, err := generators.Get(format)
			if err != nil {
				t.Errorf("generator %q not found: %v", format, err)
				return
			}
			if gen.Name() != format {
				t.Errorf("expected name %q, got %q", format, gen.Name())
			}
		})
	}
}
