package generators

const (
	// GeneratedFileHeader is the comment added to generated files.
	// Used to indicate the file should not be manually edited.
	GeneratedFileHeader = "Generated by an automated build step. Do not edit."
)
