// Generated by an automated build step. Do not edit.

export namespace Users {

  export interface User {
    email: string;
    id: string;
    name?: string;
    profile?: UserProfile;
  }

  export interface UserProfile {
    avatar?: string;
    bio?: string;
    settings?: UserSettings;
  }

  export interface UserSettings {
    notifications?: boolean;
    theme?: string;
  }

  export interface CreateUserRequest {
    email: string;
    name?: string;
  }

  export interface UpdateUserRequest {
    name?: string;
    profile?: UserProfile;
  }
}

export namespace Products {

  export interface Product {
    category?: Category;
    description?: string;
    id: string;
    name: string;
    price: Price;
  }

  export interface Price {
    amount: number;
    currency: string;
  }

  export interface Category {
    id: string;
    name: string;
    parent?: Category;
  }

  export interface CreateProductRequest {
    categoryId?: string;
    description?: string;
    name: string;
    price: Price;
  }

  export interface ProductList {
    items?: Array<Product>;
    total?: number;
  }
}
