// Generated by an automated build step. Do not edit.

export interface Product {
  category?: Category;
  description?: string;
  id: string;
  name: string;
  price: Price;
}

export interface Price {
  amount: number;
  currency: "USD" | "EUR" | "GBP";
}

export interface Category {
  id: string;
  name: string;
  parent?: Category;
}
