// Generated by an automated build step. Do not edit.

export interface CreateUserRequest {
  email: string;
  name?: string;
}

export interface UpdateUserRequest {
  name?: string;
  profile?: UserProfile;
}

export interface UserProfile {
  avatar?: string;
  bio?: string;
  settings?: UserSettings;
}

export interface UserSettings {
  notifications?: boolean;
  theme?: string;
}
