// Generated by an automated build step. Do not edit.

export interface CreateUserRequest {
  email: string;
  name?: string;
}

export interface UpdateUserRequest {
  name?: string;
  profile?: UserProfile;
}
