// Generated by an automated build step. Do not edit.

import * as z from "zod";

export const apiErrorSchema = z.object({
  code: z.string(),
  details: z.record(z.string(), z.unknown()).optional(),
  message: z.string(),
  requestId: z.string().optional(),
  timestamp: z.string().datetime().optional(),
});
export const createDocumentRequestSchema = z.object({
  content: z.string().optional(),
  tags: z.array(z.string()).optional(),
  title: z.string(),
  workspaceId: z.string().uuid(),
});
export const createUserRequestSchema = z.object({
  email: z.string().email(),
  name: z.string(),
  role: z.lazy(() => userRoleSchema).optional(),
});
export const documentSchema = z.object({
  author: z.lazy(() => userSchema).optional(),
  authorId: z.string().uuid(),
  content: z.string().optional(),
  createdAt: z.string().datetime(),
  id: z.string().uuid(),
  lastViewedAt: z.string().datetime().optional(),
  status: z.lazy(() => documentStatusSchema).optional(),
  tags: z.array(z.string()).optional(),
  title: z.string(),
  updatedAt: z.string().datetime().optional(),
  viewCount: z.number().int().optional(),
  workspaceId: z.string().uuid(),
});
export const documentStatusSchema = z.enum(["draft", "published", "archived"]);
export const memberRoleSchema = z.enum(["owner", "admin", "member", "viewer"]);
export const paginatedResponseSchema = z.object({
  hasNext: z.boolean().optional(),
  hasPrev: z.boolean().optional(),
  items: z.array(z.unknown()),
  page: z.number().int(),
  pageSize: z.number().int(),
  total: z.number().int(),
});
export const planTypeSchema = z.enum(["free", "pro", "enterprise"]);
export const updateDocumentRequestSchema = z.object({
  content: z.string().optional(),
  status: z.lazy(() => documentStatusSchema).optional(),
  tags: z.array(z.string()).optional(),
  title: z.string().optional(),
});
export const updateUserRequestSchema = z.object({
  avatarUrl: z.string().url().optional().nullable(),
  name: z.string().optional(),
  role: z.lazy(() => userRoleSchema).optional(),
});
export const userSchema = z.object({
  avatarUrl: z.string().url().optional(),
  createdAt: z.string().datetime(),
  email: z.string().email(),
  id: z.string().uuid(),
  name: z.string(),
  role: z.lazy(() => userRoleSchema).optional(),
  updatedAt: z.string().datetime().optional(),
});
export const userRoleSchema = z.enum(["admin", "member", "guest"]);
export const workspaceSchema = z.object({
  createdAt: z.string().datetime(),
  description: z.string().optional(),
  id: z.string().uuid(),
  memberCount: z.number().int().optional(),
  name: z.string(),
  plan: z.lazy(() => planTypeSchema),
  slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
});
export const workspaceMemberSchema = z.object({
  joinedAt: z.string().datetime(),
  role: z.lazy(() => memberRoleSchema),
  user: z.lazy(() => userSchema).optional(),
  userId: z.string().uuid(),
  workspaceId: z.string().uuid(),
});

// Internal schema types
type ApiErrorSchemaType = z.infer<typeof apiErrorSchema>;
type CreateDocumentRequestSchemaType = z.infer<typeof createDocumentRequestSchema>;
type CreateUserRequestSchemaType = z.infer<typeof createUserRequestSchema>;
type DocumentSchemaType = z.infer<typeof documentSchema>;
type DocumentStatusSchemaType = z.infer<typeof documentStatusSchema>;
type MemberRoleSchemaType = z.infer<typeof memberRoleSchema>;
type PaginatedResponseSchemaType = z.infer<typeof paginatedResponseSchema>;
type PlanTypeSchemaType = z.infer<typeof planTypeSchema>;
type UpdateDocumentRequestSchemaType = z.infer<typeof updateDocumentRequestSchema>;
type UpdateUserRequestSchemaType = z.infer<typeof updateUserRequestSchema>;
type UserSchemaType = z.infer<typeof userSchema>;
type UserRoleSchemaType = z.infer<typeof userRoleSchema>;
type WorkspaceSchemaType = z.infer<typeof workspaceSchema>;
type WorkspaceMemberSchemaType = z.infer<typeof workspaceMemberSchema>;

// TypeScript interfaces
export interface ApiError {
  code: ApiErrorSchemaType["code"];
  details?: ApiErrorSchemaType["details"];
  message: ApiErrorSchemaType["message"];
  requestId?: ApiErrorSchemaType["requestId"];
  timestamp?: ApiErrorSchemaType["timestamp"];
}
export interface CreateDocumentRequest {
  content?: CreateDocumentRequestSchemaType["content"];
  tags?: CreateDocumentRequestSchemaType["tags"];
  title: CreateDocumentRequestSchemaType["title"];
  workspaceId: CreateDocumentRequestSchemaType["workspaceId"];
}
export interface CreateUserRequest {
  email: CreateUserRequestSchemaType["email"];
  name: CreateUserRequestSchemaType["name"];
  role?: CreateUserRequestSchemaType["role"];
}
/** A document in a workspace */
export interface Document {
  /** A user account */
  author?: DocumentSchemaType["author"];
  authorId: DocumentSchemaType["authorId"];
  /** Document content in Markdown */
  content?: DocumentSchemaType["content"];
  createdAt: DocumentSchemaType["createdAt"];
  id: DocumentSchemaType["id"];
  lastViewedAt?: DocumentSchemaType["lastViewedAt"];
  status?: DocumentSchemaType["status"];
  tags?: DocumentSchemaType["tags"];
  title: DocumentSchemaType["title"];
  updatedAt?: DocumentSchemaType["updatedAt"];
  viewCount?: DocumentSchemaType["viewCount"];
  workspaceId: DocumentSchemaType["workspaceId"];
}
export type DocumentStatus = DocumentStatusSchemaType;
export type MemberRole = MemberRoleSchemaType;
export interface PaginatedResponse {
  hasNext?: PaginatedResponseSchemaType["hasNext"];
  hasPrev?: PaginatedResponseSchemaType["hasPrev"];
  items: PaginatedResponseSchemaType["items"];
  page: PaginatedResponseSchemaType["page"];
  pageSize: PaginatedResponseSchemaType["pageSize"];
  total: PaginatedResponseSchemaType["total"];
}
export type PlanType = PlanTypeSchemaType;
export interface UpdateDocumentRequest {
  content?: UpdateDocumentRequestSchemaType["content"];
  status?: UpdateDocumentRequestSchemaType["status"];
  tags?: UpdateDocumentRequestSchemaType["tags"];
  title?: UpdateDocumentRequestSchemaType["title"];
}
export interface UpdateUserRequest {
  avatarUrl?: UpdateUserRequestSchemaType["avatarUrl"];
  name?: UpdateUserRequestSchemaType["name"];
  role?: UpdateUserRequestSchemaType["role"];
}
/** A user account */
export interface User {
  avatarUrl?: UserSchemaType["avatarUrl"];
  createdAt: UserSchemaType["createdAt"];
  email: UserSchemaType["email"];
  id: UserSchemaType["id"];
  name: UserSchemaType["name"];
  role?: UserSchemaType["role"];
  updatedAt?: UserSchemaType["updatedAt"];
}
export type UserRole = UserRoleSchemaType;
/** A workspace/organization */
export interface Workspace {
  createdAt: WorkspaceSchemaType["createdAt"];
  description?: WorkspaceSchemaType["description"];
  id: WorkspaceSchemaType["id"];
  memberCount?: WorkspaceSchemaType["memberCount"];
  name: WorkspaceSchemaType["name"];
  plan: WorkspaceSchemaType["plan"];
  slug: WorkspaceSchemaType["slug"];
}
/** A user's membership in a workspace */
export interface WorkspaceMember {
  joinedAt: WorkspaceMemberSchemaType["joinedAt"];
  role: WorkspaceMemberSchemaType["role"];
  /** A user account */
  user?: WorkspaceMemberSchemaType["user"];
  userId: WorkspaceMemberSchemaType["userId"];
  workspaceId: WorkspaceMemberSchemaType["workspaceId"];
}