// Generated by an automated build step. Do not edit.


export type Status = "active" | "inactive";

/** A user account */
export interface User {
  /** Email address */
  email: string;
  /** Unique identifier */
  id: number;
  /** Display name */
  name?: string;
}