// Generated by an automated build step. Do not edit.

import * as z from "zod";

export const addressSchema = z.object({
  city: z.string(),
  country: z.string(),
  state: z.string().optional(),
  street: z.string(),
  zipCode: z.string().optional(),
});
export const apiErrorSchema = z.object({
  code: z.string(),
  details: z.array(z.string()).optional(),
  message: z.string(),
});
export const createUserRequestSchema = z.object({
  email: z.string().email(),
  name: z.string().optional(),
  password: z.string().min(8),
  role: z.lazy(() => userRoleSchema).optional(),
});
export const paginatedResponseSchema = z.object({
  data: z.array(z.lazy(() => userSchema)),
  page: z.number().int(),
  pageSize: z.number().int(),
  total: z.number().int(),
});
export const statusSchema = z.enum(["active", "inactive", "pending", "deleted"]);
export const updateUserRequestSchema = z.object({
  address: z.lazy(() => addressSchema).optional(),
  name: z.string().optional(),
  role: z.lazy(() => userRoleSchema).optional(),
});
export const userSchema = z.object({
  address: z.lazy(() => addressSchema).optional(),
  createdAt: z.string().datetime().optional(),
  email: z.string().email(),
  id: z.string().uuid(),
  metadata: z.record(z.string(), z.unknown()).optional().nullable(),
  name: z.string().optional(),
  role: z.lazy(() => userRoleSchema),
});
export const userRoleSchema = z.enum(["admin", "user", "guest"]);

// Internal schema types
type AddressSchemaType = z.infer<typeof addressSchema>;
type ApiErrorSchemaType = z.infer<typeof apiErrorSchema>;
type CreateUserRequestSchemaType = z.infer<typeof createUserRequestSchema>;
type PaginatedResponseSchemaType = z.infer<typeof paginatedResponseSchema>;
type StatusSchemaType = z.infer<typeof statusSchema>;
type UpdateUserRequestSchemaType = z.infer<typeof updateUserRequestSchema>;
type UserSchemaType = z.infer<typeof userSchema>;
type UserRoleSchemaType = z.infer<typeof userRoleSchema>;

// TypeScript interfaces
/** A physical address */
export interface Address {
  city: AddressSchemaType["city"];
  country: AddressSchemaType["country"];
  state?: AddressSchemaType["state"];
  street: AddressSchemaType["street"];
  zipCode?: AddressSchemaType["zipCode"];
}
/** Standard API error response */
export interface ApiError {
  code: ApiErrorSchemaType["code"];
  details?: ApiErrorSchemaType["details"];
  message: ApiErrorSchemaType["message"];
}
/** Request body for creating a user */
export interface CreateUserRequest {
  email: CreateUserRequestSchemaType["email"];
  name?: CreateUserRequestSchemaType["name"];
  password: CreateUserRequestSchemaType["password"];
  /** The role of a user */
  role?: CreateUserRequestSchemaType["role"];
}
/** A paginated response wrapper */
export interface PaginatedResponse {
  data: PaginatedResponseSchemaType["data"];
  /** Current page number */
  page: PaginatedResponseSchemaType["page"];
  /** Number of items per page */
  pageSize: PaginatedResponseSchemaType["pageSize"];
  /** Total number of items */
  total: PaginatedResponseSchemaType["total"];
}
/** Resource status */
export type Status = StatusSchemaType;
/** Request body for updating a user */
export interface UpdateUserRequest {
  /** A physical address */
  address?: UpdateUserRequestSchemaType["address"];
  name?: UpdateUserRequestSchemaType["name"];
  /** The role of a user */
  role?: UpdateUserRequestSchemaType["role"];
}
/** A user in the system */
export interface User {
  /** A physical address */
  address?: UserSchemaType["address"];
  /** When the user was created */
  readonly createdAt?: UserSchemaType["createdAt"];
  /** User's email address */
  email: UserSchemaType["email"];
  /** Unique identifier for the user */
  id: UserSchemaType["id"];
  /** Additional metadata */
  metadata?: UserSchemaType["metadata"];
  /** User's display name */
  name?: UserSchemaType["name"];
  /** The role of a user */
  role: UserSchemaType["role"];
}
/** The role of a user */
export type UserRole = UserRoleSchemaType;