// Generated by an automated build step. Do not edit.

import * as z from "zod";

export const addressSchema = z.object({
  city: z.string(),
  country: z.string(),
  state: z.string().optional(),
  street: z.string(),
  zipCode: z.string().optional(),
});
export const apiErrorSchema = z.object({
  code: z.string(),
  details: z.array(z.string()).optional(),
  message: z.string(),
});
export const createUserRequestSchema = z.object({
  email: z.string().email(),
  name: z.string().optional(),
  password: z.string().min(8),
  role: z.lazy(() => userRoleSchema).optional(),
});
export const paginatedResponseSchema = z.object({
  data: z.array(z.lazy(() => userSchema)),
  page: z.number().int(),
  pageSize: z.number().int(),
  total: z.number().int(),
});
export const statusSchema = z.enum(["active", "inactive", "pending", "deleted"]);
export const updateUserRequestSchema = z.object({
  address: z.lazy(() => addressSchema).optional(),
  name: z.string().optional(),
  role: z.lazy(() => userRoleSchema).optional(),
});
export const userSchema = z.object({
  address: z.lazy(() => addressSchema).optional(),
  createdAt: z.string().datetime().optional(),
  email: z.string().email(),
  id: z.string().uuid(),
  metadata: z.record(z.string(), z.unknown()).optional().nullable(),
  name: z.string().optional(),
  role: z.lazy(() => userRoleSchema),
});
export const userRoleSchema = z.enum(["admin", "user", "guest"]);

// Inferred types
export type Address = z.infer<typeof addressSchema>;
export type ApiError = z.infer<typeof apiErrorSchema>;
export type CreateUserRequest = z.infer<typeof createUserRequestSchema>;
export type PaginatedResponse = z.infer<typeof paginatedResponseSchema>;
export type Status = z.infer<typeof statusSchema>;
export type UpdateUserRequest = z.infer<typeof updateUserRequestSchema>;
export type User = z.infer<typeof userSchema>;
export type UserRole = z.infer<typeof userRoleSchema>;