# Generated by an automated build step. Do not edit.

from typing import TypedDict, NotRequired, Literal, Union, List, Dict, Any
from enum import Enum

class Address(TypedDict):
    """A physical address"""
    city: str
    country: str
    state: NotRequired[str]
    street: str
    zip_code: NotRequired[str]

class ApiError(TypedDict):
    """Standard API error response"""
    code: str
    details: NotRequired[List[str]]
    message: str

class CreateUserRequest(TypedDict):
    """Request body for creating a user"""
    email: str
    name: NotRequired[str]
    password: str
    role: NotRequired["UserRole"]
    """The role of a user"""

class PaginatedResponse(TypedDict):
    """A paginated response wrapper"""
    data: List["User"]
    page: int
    """Current page number"""

    page_size: int
    """Number of items per page"""

    total: int
    """Total number of items"""

class Status(str, Enum):
    """Resource status"""
    ACTIVE = "active"
    INACTIVE = "inactive"
    PENDING = "pending"
    DELETED = "deleted"

class UpdateUserRequest(TypedDict, total=False):
    """Request body for updating a user"""
    address: "Address"
    """A physical address"""

    name: str
    role: "UserRole"
    """The role of a user"""

class User(TypedDict):
    """A user in the system"""
    address: NotRequired["Address"]
    """A physical address"""

    created_at: NotRequired[str]
    """When the user was created"""

    email: str
    """User's email address"""

    id: str
    """Unique identifier for the user"""

    metadata: NotRequired[Dict[str, Any] | None]
    """Additional metadata"""

    name: NotRequired[str]
    """User's display name"""

    role: "UserRole"
    """The role of a user"""

class UserRole(str, Enum):
    """The role of a user"""
    ADMIN = "admin"
    USER = "user"
    GUEST = "guest"
