/**
 * Shared types package for the monorepo.
 *
 * This package re-exports domain-organized types generated by sparktype.
 * Other packages can import these types directly.
 */

// Re-export all domain namespaces from generated types
export * from "./types/domains";

// You can also add shared utilities that use these types

import type { Users, Documents } from "./types/domains";

/**
 * Check if a user has admin privileges.
 */
export function isAdmin(user: Users.User): boolean {
  return user.role === "admin";
}

/**
 * Check if a document is editable based on its status.
 */
export function isEditable(doc: Documents.Document): boolean {
  return doc.status === "draft";
}

/**
 * Format a user's display name with role badge.
 */
export function formatUserWithRole(user: Users.User): string {
  const roleBadge = user.role === "admin" ? " [Admin]" : "";
  return `${user.name}${roleBadge}`;
}

