// Generated by an automated build step. Do not edit.

import * as z from "zod";

// TypeScript Interfaces

/**
 * A physical address
 */
export interface Address {
  city: string;
  country: string;
  state?: string;
  street: string;
  zipCode?: string;
}

/**
 * Standard API error response
 */
export interface ApiError {
  code: string;
  details?: Array<string>;
  message: string;
}

/**
 * Request body for creating a user
 */
export interface CreateUserRequest {
  email: string;
  name?: string;
  password: string;
  /** The role of a user */
  role?: UserRole;
}

/**
 * A paginated response wrapper
 */
export interface PaginatedResponse {
  data: Array<User>;
  /** Current page number */
  page: number;
  /** Number of items per page */
  pageSize: number;
  /** Total number of items */
  total: number;
}

/**
 * Resource status
 */
export enum Status {
  Active = "active",
  Inactive = "inactive",
  Pending = "pending",
  Deleted = "deleted",
}

/**
 * Request body for updating a user
 */
export interface UpdateUserRequest {
  /** A physical address */
  address?: Address;
  name?: string;
  /** The role of a user */
  role?: UserRole;
}

/**
 * A user in the system
 */
export interface User {
  /** A physical address */
  address?: Address;
  /** When the user was created */
  readonly createdAt?: string;
  /** User's email address */
  email: string;
  /** Unique identifier for the user */
  id: string;
  /** Additional metadata */
  metadata?: Record<string, unknown> | null;
  /** User's display name */
  name?: string;
  /** The role of a user */
  role: UserRole;
}

/**
 * The role of a user
 */
export enum UserRole {
  Admin = "admin",
  User = "user",
  Guest = "guest",
}

// Zod Schemas

export const addressSchema = z.object({
  city: z.string(),
  country: z.string(),
  state: z.string().optional(),
  street: z.string(),
  zipCode: z.string().optional(),
});

export const apiErrorSchema = z.object({
  code: z.string(),
  details: z.array(z.string()).optional(),
  message: z.string(),
});

export const createUserRequestSchema = z.object({
  email: z.string().email(),
  name: z.string().optional(),
  password: z.string().min(8),
  role: z.lazy(() => userRoleSchema).optional(),
});

export const paginatedResponseSchema = z.object({
  data: z.array(z.lazy(() => userSchema)),
  page: z.number().int(),
  pageSize: z.number().int(),
  total: z.number().int(),
});

export const statusSchema = z.enum([
  "active",
  "inactive",
  "pending",
  "deleted",
]);

export const updateUserRequestSchema = z.object({
  address: z.lazy(() => addressSchema).optional(),
  name: z.string().optional(),
  role: z.lazy(() => userRoleSchema).optional(),
});

export const userSchema = z.object({
  address: z.lazy(() => addressSchema).optional(),
  createdAt: z.string().datetime().optional(),
  email: z.string().email(),
  id: z.string().uuid(),
  metadata: z.record(z.string(), z.unknown()).optional().nullable(),
  name: z.string().optional(),
  role: z.lazy(() => userRoleSchema),
});

export const userRoleSchema = z.enum(["admin", "user", "guest"]);
