// Generated by an automated build step. Do not edit.

import * as z from "zod";

/**
 * A physical address
 */
export const addressSchema = z.object({
  city: z.string(),
  country: z.string(),
  state: z.string().optional(),
  street: z.string(),
  zipCode: z.string().optional(),
});

/**
 * Standard API error response
 */
export const apiErrorSchema = z.object({
  code: z.string(),
  details: z.array(z.string()).optional(),
  message: z.string(),
});

/**
 * Request body for creating a user
 */
export const createUserRequestSchema = z.object({
  email: z.string().email(),
  name: z.string().optional(),
  password: z.string().min(8),
  /** The role of a user */
  role: z.lazy(() => userRoleSchema).optional(),
});

/**
 * A paginated response wrapper
 */
export const paginatedResponseSchema = z.object({
  data: z.array(z.lazy(() => userSchema)),
  /** Current page number */
  page: z.number().int(),
  /** Number of items per page */
  pageSize: z.number().int(),
  /** Total number of items */
  total: z.number().int(),
});

/**
 * Resource status
 */
export const statusSchema = z.enum([
  "active",
  "inactive",
  "pending",
  "deleted",
]);

/**
 * Request body for updating a user
 */
export const updateUserRequestSchema = z.object({
  /** A physical address */
  address: z.lazy(() => addressSchema).optional(),
  name: z.string().optional(),
  /** The role of a user */
  role: z.lazy(() => userRoleSchema).optional(),
});

/**
 * A user in the system
 */
export const userSchema = z.object({
  /** A physical address */
  address: z.lazy(() => addressSchema).optional(),
  /** When the user was created */
  createdAt: z.string().datetime().optional(),
  /** User's email address */
  email: z.string().email(),
  /** Unique identifier for the user */
  id: z.string().uuid(),
  /** Additional metadata */
  metadata: z.record(z.string(), z.unknown()).optional().nullable(),
  /** User's display name */
  name: z.string().optional(),
  /** The role of a user */
  role: z.lazy(() => userRoleSchema),
});

/**
 * The role of a user
 */
export const userRoleSchema = z.enum(["admin", "user", "guest"]);

// Inferred types
export type Address = z.infer<typeof addressSchema>;
export type ApiError = z.infer<typeof apiErrorSchema>;
export type CreateUserRequest = z.infer<typeof createUserRequestSchema>;
export type PaginatedResponse = z.infer<typeof paginatedResponseSchema>;
export type Status = z.infer<typeof statusSchema>;
export type UpdateUserRequest = z.infer<typeof updateUserRequestSchema>;
export type User = z.infer<typeof userSchema>;
export type UserRole = z.infer<typeof userRoleSchema>;
