// Code generated by an automated build step. Do not edit.

package api

import "time"

// Address A physical address
type Address struct {
	City    string  `json:"city"`
	Country string  `json:"country"`
	State   *string `json:"state,omitempty"`
	Street  string  `json:"street"`
	ZipCode *string `json:"zipCode,omitempty"`
}

// ApiError Standard API error response
type ApiError struct {
	Code    string   `json:"code"`
	Details []string `json:"details,omitempty"`
	Message string   `json:"message"`
}

// CreateUserRequest Request body for creating a user
type CreateUserRequest struct {
	Email    string  `json:"email"`
	Name     *string `json:"name,omitempty"`
	Password string  `json:"password"`
	// The role of a user
	Role *UserRole `json:"role,omitempty"`
}

// PaginatedResponse A paginated response wrapper
type PaginatedResponse struct {
	Data []User `json:"data"`
	// Current page number
	Page int `json:"page"`
	// Number of items per page
	PageSize int `json:"pageSize"`
	// Total number of items
	Total int `json:"total"`
}

// Status Resource status
type Status string

const (
	StatusActive   Status = "active"
	StatusInactive Status = "inactive"
	StatusPending  Status = "pending"
	StatusDeleted  Status = "deleted"
)

// UpdateUserRequest Request body for updating a user
type UpdateUserRequest struct {
	// A physical address
	Address *Address `json:"address,omitempty"`
	Name    *string  `json:"name,omitempty"`
	// The role of a user
	Role *UserRole `json:"role,omitempty"`
}

// User A user in the system
type User struct {
	// A physical address
	Address *Address `json:"address,omitempty"`
	// When the user was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// User's email address
	Email string `json:"email"`
	// Unique identifier for the user
	ID string `json:"id"`
	// Additional metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// User's display name
	Name *string `json:"name,omitempty"`
	// The role of a user
	Role UserRole `json:"role"`
}

// UserRole The role of a user
type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
	UserRoleGuest UserRole = "guest"
)
