# Generated by an automated build step. Do not edit.

from typing import TypedDict, NotRequired, Literal, Union, List, Dict, Any
from enum import Enum


# A physical address
class Address(TypedDict):
    city: str
    country: str
    state: NotRequired[str]
    street: str
    zip_code: NotRequired[str]


# Standard API error response
class ApiError(TypedDict):
    code: str
    details: NotRequired[List[str]]
    message: str


# Request body for creating a user
class CreateUserRequest(TypedDict):
    email: str
    name: NotRequired[str]
    password: str
    # The role of a user
    role: NotRequired["UserRole"]


# A paginated response wrapper
class PaginatedResponse(TypedDict):
    data: List["User"]
    # Current page number
    page: int
    # Number of items per page
    page_size: int
    # Total number of items
    total: int


# Resource status
class Status(str, Enum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    PENDING = "pending"
    DELETED = "deleted"


# Request body for updating a user
class UpdateUserRequest(TypedDict, total=False):
    # A physical address
    address: "Address"
    name: str
    # The role of a user
    role: "UserRole"


# A user in the system
class User(TypedDict):
    # A physical address
    address: NotRequired["Address"]
    # When the user was created
    created_at: NotRequired[str]
    # User's email address
    email: str
    # Unique identifier for the user
    id: str
    # Additional metadata
    metadata: NotRequired[Dict[str, Any] | None]
    # User's display name
    name: NotRequired[str]
    # The role of a user
    role: "UserRole"


# The role of a user
class UserRole(str, Enum):
    ADMIN = "admin"
    USER = "user"
    GUEST = "guest"
