// Generated by an automated build step. Do not edit.

/** Pagination parameters */
export interface Pagination {
  /** Current page number */
  page: number;
  /** Items per page */
  pageSize: number;
  /** Total items */
  total: number;
}

/** Sort direction */
export type SortOrder = "asc" | "desc";

/** Standard API response wrapper */
export interface ApiResponse {
  data?: data;
  error?: string;
  success: boolean;
}

export namespace API {
  /** A user in the system */
  export interface User {
    /** A physical address */
    address?: Address;
    /** When the user was created */
    readonly createdAt?: string;
    /** User's email address */
    email: string;
    /** Unique identifier for the user */
    id: string;
    /** Additional metadata */
    metadata?: Record<string, unknown> | null;
    /** User's display name */
    name?: string;
    /** The role of a user */
    role: UserRole;
  }
  /** The role of a user */
  export type UserRole = "admin" | "user" | "guest";
  /** Request body for creating a user */
  export interface CreateUserRequest {
    email: string;
    name?: string;
    password: string;
    /** The role of a user */
    role?: UserRole;
  }
  /** Request body for updating a user */
  export interface UpdateUserRequest {
    /** A physical address */
    address?: Address;
    name?: string;
    /** The role of a user */
    role?: UserRole;
  }
}
