# Generated by an automated build step. Do not edit.

from typing import TypedDict, NotRequired, Literal, Union, List, Dict, Any
from enum import Enum

class CreateProjectRequest(TypedDict):
    """Request body for creating a project"""
    color: NotRequired[str]
    description: NotRequired[str]
    name: str

class CreateTaskRequest(TypedDict):
    """Request body for creating a task"""
    assignee_id: NotRequired[str]
    description: NotRequired[str]
    due_date: NotRequired[str]
    estimated_hours: NotRequired[float]
    labels: NotRequired[List[str]]
    priority: NotRequired["Priority"]
    """Task priority level"""

    project_id: NotRequired[str]
    title: str

class ErrorResponse(TypedDict):
    """Standard error response"""
    error: str
    """Error code"""

    message: str
    """Human-readable error message"""

    request_id: NotRequired[str]
    """Request ID for debugging"""

class Priority(str, Enum):
    """Task priority level"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"

class Project(TypedDict):
    """A project containing tasks"""
    color: NotRequired[str]
    """Hex color code for the project"""

    created_at: str
    description: NotRequired[str]
    id: str
    name: str
    owner: NotRequired["User"]
    """A user in the system"""

    task_count: NotRequired[int]
    """Number of tasks in the project"""

class Task(TypedDict):
    """A task in the system"""
    assignee: NotRequired["User"]
    """A user in the system"""

    completed_at: NotRequired[str]
    """When the task was completed"""

    created_at: str
    """When the task was created"""

    description: NotRequired[str]
    """Detailed task description"""

    due_date: NotRequired[str]
    """Task due date"""

    estimated_hours: NotRequired[float]
    """Estimated hours to complete"""

    id: str
    """Unique task identifier"""

    labels: NotRequired[List[str]]
    priority: "Priority"
    """Task priority level"""

    project_id: NotRequired[str]
    """ID of the project this task belongs to"""

    status: "TaskStatus"
    """Task status"""

    title: str
    """Task title"""

    updated_at: NotRequired[str]
    """When the task was last updated"""

class TaskStatus(str, Enum):
    """Task status"""
    TODO = "todo"
    IN_PROGRESS = "in_progress"
    REVIEW = "review"
    DONE = "done"
    CANCELLED = "cancelled"

class UpdateTaskRequest(TypedDict, total=False):
    """Request body for updating a task"""
    assignee_id: str | None
    description: str
    due_date: str | None
    estimated_hours: float | None
    labels: List[str]
    priority: "Priority"
    """Task priority level"""

    status: "TaskStatus"
    """Task status"""

    title: str

class User(TypedDict):
    """A user in the system"""
    avatar_url: NotRequired[str]
    email: str
    id: str
    name: str

class ValidationError(TypedDict):
    """Validation error response"""
    detail: List["ValidationErrorDetail"]

class ValidationErrorDetail(TypedDict):
    loc: List[str]
    msg: str
    type: str
