// Generated by an automated build step. Do not edit.

/** Request to add an item to cart */
export interface AddToCartRequest {
  productId: string;
  quantity: number;
}

/** Physical address */
export interface Address {
  city: string;
  /** ISO 3166-1 alpha-2 country code */
  country: string;
  line1: string;
  line2?: string;
  postalCode: string;
  state?: string;
}

/** API error response */
export interface ApiError {
  /** Machine-readable error code */
  code: string;
  details?: Array<ErrorDetail>;
  /** Human-readable error message */
  message: string;
  /** Request ID for debugging */
  requestId?: string;
}

/** Shopping cart */
export interface Cart {
  id: string;
  /** Total number of items in cart */
  itemCount?: number;
  items: Array<CartItem>;
  /** Price with currency */
  subtotal: Price;
}

/** Item in a shopping cart */
export interface CartItem {
  /** Price with currency */
  price: Price;
  /** A product available for purchase */
  product?: Product;
  productId: string;
  quantity: number;
}

/** Request to create an order */
export interface CreateOrderRequest {
  /** Physical address */
  billingAddress?: Address;
  notes?: string;
  /** Physical address */
  shippingAddress: Address;
}

/** Request body for creating a product */
export interface CreateProductRequest {
  /** Product category */
  category: ProductCategory;
  description?: string;
  images?: Array<{ alt: string; isPrimary?: boolean; url: string }>;
  name: string;
  price: price;
  stockCount?: number;
  tags?: Array<string>;
}

/** Detailed error information */
export interface ErrorDetail {
  /** Error code for this field */
  code?: string;
  /** Field that caused the error */
  field: string;
  /** Error description */
  message: string;
}

/** A customer order */
export interface Order {
  /** Physical address */
  billingAddress?: Address;
  createdAt: string;
  id: string;
  items: Array<OrderItem>;
  /** Physical address */
  shippingAddress: Address;
  /** Order status */
  status: OrderStatus;
  /** Price with currency */
  total: Price;
  updatedAt?: string;
}

/** Item in an order */
export interface OrderItem {
  productId: string;
  productName: string;
  quantity: number;
  /** Price with currency */
  totalPrice: Price;
  /** Price with currency */
  unitPrice: Price;
}

/** Order status */
export enum OrderStatus {
  Pending = "pending",
  Confirmed = "confirmed",
  Processing = "processing",
  Shipped = "shipped",
  Delivered = "delivered",
  Cancelled = "cancelled",
}

/** Price with currency */
export interface Price {
  /** Price amount in smallest currency unit (cents) */
  amount: number;
  /** ISO 4217 currency code */
  currency: string;
  /** Human-readable formatted price */
  readonly formatted?: string;
}

/** A product available for purchase */
export interface Product {
  /** Product category */
  category: ProductCategory;
  readonly createdAt?: string;
  /** Detailed product description */
  description?: string;
  /** Unique product identifier */
  id: string;
  images?: Array<ProductImage>;
  /** Whether the product is currently in stock */
  inStock: boolean;
  /** Product name */
  name: string;
  /** Price with currency */
  price: Price;
  /** Number of items in stock */
  stockCount?: number;
  tags?: Array<string>;
}

/** Product category */
export enum ProductCategory {
  Electronics = "electronics",
  Clothing = "clothing",
  Home = "home",
  Books = "books",
  Sports = "sports",
  Toys = "toys",
}

/** Product image */
export interface ProductImage {
  alt: string;
  isPrimary?: boolean;
  url: string;
}

/** Paginated list of products */
export interface ProductListResponse {
  hasMore?: boolean;
  items: Array<Product>;
  limit: number;
  offset: number;
  /** Total number of products matching the query */
  total: number;
}
